/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';
import { useMutation } from '@tanstack/react-query';

import { axiosInstance } from '../axios-instance';
export type ConceptValidationDtoViolations = {
  [key: string]: RuleViolationDto;
};

export interface ConceptValidationDto {
  conceptIri?: string;
  violations?: ConceptValidationDtoViolations;
}

export interface ConversionResponseDto {
  output?: string;
  errorMessage?: string;
  validationResults?: ValidationResultsDto;
  validationReport?: DetailedValidationReportDto;
}

export type DetailedValidationReportDtoValidation = {
  [key: string]: ConceptValidationDto;
};

export interface DetailedValidationReportDto {
  ontology?: OntologyInfoDto;
  validation?: DetailedValidationReportDtoValidation;
}

export type OntologyInfoDtoName = { [key: string]: string };

export type OntologyInfoDtoDescription = { [key: string]: string };

export interface OntologyInfoDto {
  name?: OntologyInfoDtoName;
  description?: OntologyInfoDtoDescription;
}

export interface RuleViolationDto {
  name?: string;
  description?: string;
  level?: string;
  severity?: string;
  value?: string;
}

export interface SeverityGroupDto {
  severity?: string;
  count?: number;
  description?: string;
}

export interface ValidationResultsDto {
  severityGroups?: SeverityGroupDto[];
}

export type ConvertFileParams = {
  output?: string;
  removeInvalidSources?: boolean;
  includeDetailedReport?: boolean;
};

export type ConvertFileBody = {
  file: Blob;
};

export type DownloadDetailedValidationReportCSVParams = {
  filename?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const convertFile = (
  formData: FormData, // ConvertFileBody & ConvertFileParams
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ConversionResponseDto>(
    {
      url: `/api/converter/convert`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options,
  );
};

export const getConvertFileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof convertFile>>,
    TError,
    FormData, // ConvertFileBody & ConvertFileParams
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof convertFile>>,
  TError,
  FormData, // ConvertFileBody & ConvertFileParams
  TContext
> => {
  const mutationKey = ['convertFile'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof convertFile>>,
    FormData // ConvertFileBody & ConvertFileParams
  > = (formData) => {
    return convertFile(formData, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConvertFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof convertFile>>
>;
export type ConvertFileMutationBody = ConvertFileBody;
export type ConvertFileMutationError = unknown;

export const useConvertFile = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof convertFile>>,
      TError,
      FormData, // ConvertFileBody & ConvertFileParams
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof convertFile>>,
  TError,
  FormData, // ConvertFileBody & ConvertFileParams
  TContext
> => {
  const mutationOptions = getConvertFileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const downloadDetailedValidationReportCSV = (
  formData: FormData, // DetailedValidationReportDto & DownloadDetailedValidationReportCSVParams
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<string>(
    {
      url: `/api/converter/convert/detailed-report/csv`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options,
  );
};

export const getDownloadDetailedValidationReportCSVMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof downloadDetailedValidationReportCSV>>,
    TError,
    FormData, // DetailedValidationReportDto & DownloadDetailedValidationReportCSVParams
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof downloadDetailedValidationReportCSV>>,
  TError,
  FormData, // DetailedValidationReportDto & DownloadDetailedValidationReportCSVParams
  TContext
> => {
  const mutationKey = ['downloadDetailedValidationReportCSV'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof downloadDetailedValidationReportCSV>>,
    FormData // DetailedValidationReportDto & DownloadDetailedValidationReportCSVParams
  > = (formData) => {
    return downloadDetailedValidationReportCSV(formData, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DownloadDetailedValidationReportCSVMutationResult = NonNullable<
  Awaited<ReturnType<typeof downloadDetailedValidationReportCSV>>
>;
export type DownloadDetailedValidationReportCSVMutationBody =
  DetailedValidationReportDto;
export type DownloadDetailedValidationReportCSVMutationError = unknown;

export const useDownloadDetailedValidationReportCSV = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof downloadDetailedValidationReportCSV>>,
      TError,
      FormData, // DetailedValidationReportDto & DownloadDetailedValidationReportCSVParams
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof downloadDetailedValidationReportCSV>>,
  TError,
  FormData, // DetailedValidationReportDto & DownloadDetailedValidationReportCSVParams
  TContext
> => {
  const mutationOptions =
    getDownloadDetailedValidationReportCSVMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
